export const projectsData = {
  en: {
    workProjects: [
      {
        name: "UI Campaign Patterns",
        company: "Alfons Digital (8.1.2024 - 22.5.2024)",
        desc: "Built reusable WordPress patterns for creating dynamic case showcase pages. Designed flexible components to streamline client project setups.",
        image: "images/projects/ui-campaign-patterns.jpg",
        tech: ["WordPress", "CSS"],
        highlights: [
          "Custom Gutenberg React block components",
          "Reusable pattern library for multiple clients",
          "Responsive design across all breakpoints",
          "Accessibility testing (WCAG compliance)",
        ],
      },
      {
        name: "HSKK Marketing Site",
        company: "Alfons Digital",
        desc: "Marketing website for Helsingin seudun kauppakamari showcasing their various services with custom layouts and optimized UX.",
        image: "images/projects/hskk-marketing.jpg",
        tech: ["WordPress", "PHP", "CSS"],
        highlights: [
          "Custom post types for services",
          "Mobile-responsive design",
          "Performance optimization",
          "Accessibility testing",
        ],
      },
      {
        name: "Future School",
        company: "Alfons Digital",
        desc: "Story-based survey website for Lasten ja nuortensäätiö. Interactive React components guide users through narratives with form collection.",
        image: "images/projects/future-school.jpg",
        tech: ["React", "WordPress"],
        highlights: [
          "Interactive story-based UI flow",
          "Dynamic form handling",
          "Custom data collection",
          "Accessibility compliance verified",
        ],
      },
      {
        name: "Impact Library & Network",
        company: "Alfons Digital",
        desc: "Dual-component project featuring a workshop directory (Impact Library) and an interactive map (Impact Network) using custom post types.",
        image: "images/projects/impact-library-network.jpg",
        tech: ["React", "WordPress", "PHP", "JavaScript"],
        highlights: [
          "Custom post type taxonomy system",
          "Interactive map with markers",
          "Category filtering for workshops",
          "Full accessibility testing suite",
        ],
      },
    ],
    personalProjects: [
      {
        name: "Portfolio",
        desc: "Personal portfolio website built with Astro showcasing projects, experience, and skills. Modern, performant, and fully responsive.",
        url: "https://github.com/MWxzy/portfolio",
        tech: ["Astro", "CSS", "JavaScript", "TypeScript"],
        highlights: [
          "Static site generation with Astro",
          "Fast performance & SEO optimized",
          "Responsive design",
          "Dark theme with smooth transitions",
        ],
      },
      {
        name: "Resume Builder",
        desc: "A resume/CV builder application that allows users to create and customize their own resumes using a JSON-based format.",
        url: "https://github.com/MWxzy/resume-builder",
        tech: ["TypeScript", "React", "Vite"],
        highlights: [
          "JSON-based resume data format",
          "Customizable templates",
          "Export to PDF",
          "Responsive design",
        ],
      },
      {
        name: "UniAteriat",
        desc: "A web application project showcasing modern JavaScript practices and interactive UI components.",
        url: "https://github.com/MWxzy/web-sovellus",
        liveUrl: "https://users.metropolia.fi/~kaspelai/web-app/",
        tech: ["JavaScript", "CSS", "HTML"],
        highlights: [
          "Interactive components",
          "Modern JavaScript ES6+",
          "CSS animations",
        ],
      },
      {
        name: "Breakframe",
        desc: "A responsive device preview tool that lets you inspect how websites look across desktop, laptop, tablet, and mobile screen sizes.",
        url: "https://github.com/MWxzy/breakframe",
        liveUrl: "",
        tech: ["Vue", "TypeScript", "CSS", "Vite"],
        highlights: [
          "Responsive device previews",
          "Interactive hover and focus states",
          "Desktop, laptop, tablet, and mobile layouts",
        ],
      },
    ],
    groupProjects: [
      {
        name: "City Sushi",
        desc: "A restaurant website for City Sushi featuring menu, location, and ordering information.",
        url: "https://github.com/MWxzy/citysushi-react",
        liveUrl: "https://citysushi-frontend.vercel.app/",
        tech: ["HTML", "CSS", "JavaScript", "React", "Tailwind"],
        highlights: [
          "Interactive menu display",
          "Responsive layout",
          "Smooth animations",
        ],
      },
      {
        name: "University Admission Queue Simulation",
        desc: "University admission queue system simulation project. Demonstrates queue data structures and algorithms for processing student admissions.",
        url: "https://github.com/MWxzy/University-Admission-Queue-System-Simulation",
        tech: ["Java", "CSS"],
        highlights: [
          "Queue data structure implementation",
          "Student admission simulation",
          "Visual queue representation",
        ],
      },
      {
        name: "Freightfall",
        desc: "A collaborative group project creating an interactive game/application.",
        url: "https://github.com/Hexdoktor/Freightfall_ryhm-projekti",
        tech: ["Python", "HTML", "JavaScript", "CSS"],
        highlights: [
          "Team collaboration using Git",
          "Cross-language integration",
          "Interactive gameplay mechanics",
        ],
      },
    ],
    additionalClients: [
      "Helsingin seudun kauppakamari",
      "Turun seudun kauppakamari",
      "Kauppakamari – KoulutusOnline",
      "Kauppakamari - TyösuhdePRO",
      "Kauppakamari – KauppakamariTieto",
      "Kirjailijalehti",
      "Kirjailijaliitto",
      "Forumvirium",
      "Kiipeilyareena",
      "h2clusters",
      "Lukuliike",
      "Nordic label",
      "political party website",
      "Alfons Education & Alfons Digital websites",
    ],
  },
  fi: {
    workProjects: [
      {
        name: "UI Campaign Patterns",
        company: "Alfons Digital (8.1.2024 - 22.5.2024)",
        desc: "Rakensin uudelleenkäytettäviä WordPress-malleja dynaamisille case-esittelysivuille.",
        image: "images/projects/ui-campaign-patterns.jpg",
        tech: ["WordPress", "CSS"],
        highlights: [
          "Mukautetut Gutenberg React -lohkokomponentit",
          "Uudelleenkäytettävä mallien kirjasto useille asiakkaille",
          "Responsiiviinen muotoilu kaikilla resoluutioilla",
          "Saavutettavuustestaus (WCAG-vaatimustenmukaisuus)",
        ],
      },
      {
name: "HSKK Marketing Site",
        company: "Alfons Digital",
        desc: "Markkinointiverkkosivusto Helsingin seudun kauppakamarin palveluille mukautetulla asettelulla ja optimoidulla käyttäjäkokemuksella.",
        image: "images/projects/hskk-marketing.jpg",
        tech: ["WordPress", "PHP", "CSS"],
        highlights: [
          "Mukautetut palveluiden postit",
          "Mobiiliystävällinen muotoilu",
          "Suorituskyvyn optimointi",
          "Saavutettavuustestaus",
        ],
      },
      {
        name: "Future School",
        company: "Alfons Digital",
        desc: "Tarinaperustainen kysely verkkosivusto Lasten ja nuortensäätiölle. Interaktiiviset React-komponentit ohjaavat käyttäjiä tarinapohjaisen kokemuksen läpi ja keräävät lomaketietoja.",
        image: "images/projects/future-school.jpg",
        tech: ["React", "WordPress"],
        highlights: [
          "Interaktiivinen tarinapohjainen käyttöliittymätyönkulku",
          "Dynaaminen lomakkeiden käsittely",
          "Mukautettu tiedonkeruu",
          "Saavutettavuuden vaatimustenmukaisuus vahvistettu",
        ],
      },
      {
        name: "Impact Library & Network",
        company: "Alfons Digital",
        desc: "Kaksiosaisessa projektissa on työpajojen hakemisto (Impact Library) ja interaktiivinen kartta (Impact Network) mukautetuilla post tyypeillä.",
        image: "images/projects/impact-library-network.jpg",
        tech: ["React", "WordPress", "PHP", "JavaScript"],
        highlights: [
          "Mukautettu postityyppien taksonomiajärjestelmä",
          "Interaktiivinen kartta merkkeineen",
          "Työpajojen luokkien suodatus",
          "Täydellinen saavutettavuuden testisarja",
        ],
      },
    ],
    personalProjects: [
      {
        name: "Portfolio",
        desc: "Henkilökohtainen portfolioverkkosivusto rakennettu Astrolla, joka esittelee projekteja, kokemusta ja taitoja. Moderni, suorituskykyinen ja täysin responsiivinen.",
        url: "https://github.com/MWxzy/portfolio",
        tech: ["Astro", "CSS", "JavaScript", "TypeScript"],
        highlights: [
          "Staattinen sivugenerointi Astrolla",
          "Nopea suorituskyky ja SEO-optimoitu",
          "Responsiivinen muotoilu",
          "Tumma teema sulavilla siirtymillä",
        ],
      },
      {
        name: "Resume Builder",
        desc: "Ansioluettelo/CV-rakentajasovellus, jonka avulla käyttäjät voivat luoda ja mukauttaa omia ansioluetteloitaan JSON-pohjaisella muodolla.",
        url: "https://github.com/MWxzy/resume-builder",
        tech: ["TypeScript", "React", "Vite"],
        highlights: [
          "JSON-pohjainen ansioluettelon tietomuoto",
          "Mukautettavat mallit",
          "Vienti PDF-muotoon",
          "Responsiivinen muotoilu",
        ],
      },
      {
        name: "UniAteriat",
        desc: "Verkkosovellusprojekti, joka esittelee nykyaikaisia JavaScript-käytäntöjä ja interaktiivisia käyttöliittymäkomponentteja.",
        url: "https://github.com/MWxzy/web-sovellus",
        liveUrl: "https://users.metropolia.fi/~kaspelai/web-app/",
        tech: ["JavaScript", "CSS", "HTML"],
        highlights: [
          "Interaktiiviset komponentit",
          "Moderni JavaScript ES6+",
          "CSS-animaatiot",
        ],
      },
      {
        name: "Breakframe",
        desc: "Responsiivinen laitteiden esikatselusovellus, jonka avulla voit tarkastella, miltä verkkosivusto näyttää työpöydällä, kannettavalla tietokoneella, tabletilla ja mobiililaitteella.",
        url: "https://github.com/MWxzy/breakframe",
        liveUrl: "",
        tech: ["Vue", "TypeScript", "CSS", "Vite"],
        highlights: [
          "Responsiiviset laite-esikatselut",
          "Interaktiiviset hover- ja fokusointitilat",
          "Työpöytä-, kannettava-, tabletti- ja mobiilinäkymät",
        ],
      },
    ],
    groupProjects: [
      {
        name: "City Sushi",
        desc: "City Sushin ravintolaverkkosivusto, jossa on valikko, sijainti ja tilaustieto.",
        url: "https://github.com/MWxzy/citysushi-react",
        liveUrl: "https://citysushi-frontend.vercel.app/",
        tech: ["HTML", "CSS", "JavaScript", "React", "Tailwind"],
        highlights: [
          "Interaktiivinen valikon näyttö",
          "Responsiivinen asettelu",
          "Sujuvat animaatiot",
        ],
      },
      {
        name: "University Admission Queue Simulation",
        desc: "Yliopiston hakujonosimulaatioprojekti. Havainnollistaa jonodatarakenteita ja algoritmeja opiskelijavalintojen käsittelyssä.",
        url: "https://github.com/MWxzy/University-Admission-Queue-System-Simulation",
        tech: ["Java", "CSS"],
        highlights: [
          "Jonotietorakenteen toteutus",
          "Opiskelijavalintojen simulointi",
          "Visuaalinen jonon esitys",
        ],
      },
      {
        name: "Freightfall",
        desc: "Yhteistyöprojekti, jossa luotiin interaktiivinen peli/sovellus.",
        url: "https://github.com/Hexdoktor/Freightfall_ryhm-projekti",
        tech: ["Python", "HTML", "JavaScript", "CSS"],
        highlights: [
          "Tiimin yhteistyö Gitissä",
          "Kielten välinen integraatio",
          "Interaktiiviset pelimekaniikat",
        ],
      },
    ],
    additionalClients: [
      "Helsingin seudun kauppakamari",
      "Turun seudun kauppakamari",
      "Kauppakamari – KoulutusOnline",
      "Kauppakamari - TyösuhdePRO",
      "Kauppakamari – KauppakamariTieto",
      "Kirjailijalehti",
      "Kirjailijaliitto",
      "Forumvirium",
      "Kiipeilyareena",
      "h2clusters",
      "Lukuliike",
      "Nordic label",
      "poliittisen puolueen sivusto",
      "Alfons Education & Alfons Digital -verkkosivustot",
    ],
  },
  sv: {
    workProjects: [
      {
        name: "UI Campaign Patterns",
        company: "Alfons Digital (8.1.2024 - 22.5.2024)",
        desc: "Byggde återanvändbara WordPress-mönster för att skapa dynamiska fallstudiesidor. Designade flexibla komponenter för att effektivisera klientprojektkonfigurationer.",
        image: "images/projects/ui-campaign-patterns.jpg",
        tech: ["WordPress", "CSS"],
        highlights: [
          "Anpassade Gutenberg React-blockkomponenter",
          "Återanvändbar mönsterbibliotek för flera klienter",
          "Responsiv design över alla brytpunkter",
          "Tillgänglighetstestning (WCAG-överensstämmelse)",
        ],
      },
      {
        name: "HSKK Marketing Site",
        company: "Alfons Digital",
        desc: "Marknadsföringswebbplats för Helsingfors regionala handelskammare med anpassade layouter och optimerad användarupplevelse.",
        image: "images/projects/hskk-marketing.jpg",
        tech: ["WordPress", "PHP", "CSS"],
        highlights: [
          "Anpassade inläggstyper för tjänster",
          "Mobilvänlig design",
          "Prestandaoptimering",
          "Tillgänglighetstestning",
        ],
      },
      {
        name: "Future School",
        company: "Alfons Digital",
        desc: "Historiebaskerad enkätwebbplats för Barn- och ungdomsstiftelsen. Interaktiva React-komponenter guidar användare genom narrativ med formulärsamling.",
        image: "images/projects/future-school.jpg",
        tech: ["React", "WordPress"],
        highlights: [
          "Interaktiv historiebaserad gränssnittsflöde",
          "Dynamisk formulärhantering",
          "Anpassad datainsamling",
          "Tillgänglighetsöverensstämmelse verifierad",
        ],
      },
      {
        name: "Impact Library & Network",
        company: "Alfons Digital",
        desc: "Tvådelat projekt med en workshopp-katalog (Impact Library) och en interaktiv karta (Impact Network) med anpassade inläggstyper.",
        image: "images/projects/impact-library-network.jpg",
        tech: ["React", "WordPress", "PHP", "JavaScript"],
        highlights: [
          "Anpassat inläggstyp-taxonomisystem",
          "Interaktiv karta med markörer",
          "Kategorifitrering för workshop",
          "Komplett tillgänglighetstestsvit",
        ],
      },
    ],
    personalProjects: [
      {
        name: "Portfolio",
        desc: "Personlig portföljwebbplats byggd med Astro som showcasar projekt, erfarenhet och färdigheter. Modern, prestandakraftig och helt responsiv.",
        url: "https://github.com/MWxzy/portfolio",
        tech: ["Astro", "CSS", "JavaScript", "TypeScript"],
        highlights: [
          "Statisk webbplatsgenerering med Astro",
          "Snabb prestanda & SEO-optimerad",
          "Responsiv design",
          "Mörkt tema med smidiga övergångar",
        ],
      },
      {
        name: "Resume Builder",
        desc: "En CV-byggarapplikation som gör det möjligt för användare att skapa och anpassa sina egna CV:n med ett JSON-baserat format.",
        url: "https://github.com/MWxzy/resume-builder",
        tech: ["TypeScript", "React", "Vite"],
        highlights: [
          "JSON-baserat CV-dataformat",
          "Anpassningsbara mallar",
          "Exportera till PDF",
          "Responsiv design",
        ],
      },
      {
        name: "UniAteriat",
        desc: "Ett webbapplikationsprojekt som visar moderna JavaScript-metoder och interaktiva gränssnittskomponenter.",
        url: "https://github.com/MWxzy/web-sovellus",
        liveUrl: "https://users.metropolia.fi/~kaspelai/web-app/",
        tech: ["JavaScript", "CSS", "HTML"],
        highlights: [
          "Interaktiva komponenter",
          "Modernt JavaScript ES6+",
          "CSS-animationer",
        ],
      },
      {
        name: "Breakframe",
        desc: "Ett responsivt verktyg för enhetsförhandsvisning som låter dig se hur en webbplats ser ut på dator, bärbar dator, surfplatta och mobil.",
        url: "https://github.com/MWxzy/breakframe",
        liveUrl: "",
        tech: ["Vue", "TypeScript", "CSS", "Vite"],
        highlights: [
          "Responsiva enhetsförhandsvisningar",
          "Interaktiva hover- och fokuseringslägen",
          "Vyer för dator, bärbar dator, surfplatta och mobil",
        ],
      }, 
    ],
    groupProjects: [
      {
        name: "City Sushi",
        desc: "En restaurangwebbplats för City Sushi med meny, plats och beställningsinformation.",
        url: "https://github.com/MWxzy/citysushi-react",
        liveUrl: "https://citysushi-frontend.vercel.app/",
        tech: ["HTML", "CSS", "JavaScript", "React", "Tailwind"],
        highlights: [
          "Interaktiv menybilning",
          "Responsiv layout",
          "Släta animationer",
        ],
      },
      {
        name: "University Admission Queue Simulation",
        desc: "Simuleringsprojekt för universitetsadmissionskö. Visar köadatastrukturer och algoritmer för hantering av studentadmissioner.",
        url: "https://github.com/MWxzy/University-Admission-Queue-System-Simulation",
        tech: ["Java", "CSS"],
        highlights: [
          "Köad-datastruktur-implementering",
          "Studentadmissionssimulering",
          "Visuell körepresentation",
        ],
      },
      {
        name: "Freightfall",
        desc: "Ett samarbetsprojekt som skapar ett interaktivt spel/applikation.",
        url: "https://github.com/Hexdoktor/Freightfall_ryhm-projekti",
        tech: ["Python", "HTML", "JavaScript", "CSS"],
        highlights: [
          "Teamsamarbete med Git",
          "Språkövergripande integration",
          "Interaktiv spelmekanism",
        ],
      },
    ],
    additionalClients: [
      "Helsingfors regionala handelskammare",
      "Turku regionala handelskammare",
      "Handelskammare – KoulutusOnline",
      "Handelskammare - TyösuhdePRO",
      "Handelskammare – KauppakamariTieto",
      "Kirjailijalehti",
      "Skriftförbundet",
      "Forumvirium",
      "Kiipeilyareena",
      "h2clusters",
      "Lukuliike",
      "Nordic label",
      "ett politiskt partis webbplats",
      "Alfons Education & Alfons Digital webbplatser",
    ],
  },
};
